layout = {
    'date_field': ['Spud Date', 'Completion Date', 'Release Date', 'Last Status Change'],
    'api_field': 'API',
    'type_field': 'Permitted Status',
    'status_field': 'Current Status',
    'category_field': 'Permitted Class',
    'lat_field': 'Wellhead Calculated Latitude (NAD27)',
    'lon_field': 'Wellhead Calculated Longitude (NAD27)',
    'description_layout': '\n'.join(['Permit No. %s', 
                                     'Operator: %s',
                             'Area: %s',
                             'Field: %s',
                             'Pools: %s',
                             'Well Name: %s'
                            ]),
    'description_fields': ['Permit', 'Operator', 'Area', 'Field', 'Pools', 'Well Name'],
    'type_map': {
        '': 'UNKNOWN',
        'Gas well, triple completion': 'GAS',
        'Oil & gas well, 2oil-1gas, triple comp': 'OILANDGAS',
        'Water injection, single completion': 'INJECTION',
        'Disposal injection well, Class 1': 'INJECTION',
        'Coal Bed Natural Gas': 'GAS',
        'Relief Well for Blowout': 'OTHER',
        'Information well': 'TEST',
        'Condensate well, single comp': 'OTHER',
        'Gas storage well': 'STORAGE',
        'Water alt gas injection': 'INJECTION',
        'Shale Bed Natural Gas': 'GAS',
        'Oil well, dual completion': 'OIL',
        'Unknown': 'UNKNOWN',
        'Water supply well': 'WATER',
        'Oil Well, Alt Wtr Inj, Single Comp': 'OIL',
        'Oil well, single completion': 'OIL',
        'Water injection, dual completion': 'INJECTION',
        'Gas well, dual completion': 'GAS',
        'Gas injection, single completion': 'GAS',
        'Disposal injection well, Class 2': 'INJECTION',
        'Oil & gas well, 2oil-2gas, quad comp': 'OILANDGAS',
        'Gas supply well': 'GAS',
        'Observation well': 'OBSERVATION',
        '401 Application Being Processed': 'UNKNOWN',
        'Geothermal': 'OTHER',
        'Gas well, single completion': 'GAS',
        'Gas well & Storage well': 'GAS',
    },
    'status_map': {
        'Gas well, triple completion': 'ACTIVE',
        'Permit expired': 'CANCELLED',
        'Water injection, single completion': 'ACTIVE',
        'Disposal injection well, Class 1': 'ACTIVE',
        'Gas well & Disposal well, dual comp': 'ACTIVE',
        'Information well': 'ACTIVE',
        'Shut In': 'PA',
        'Gas storage well': 'ACTIVE',
        'Water alt gas injection': 'ACTIVE',
        'Oil well, dual completion': 'ACTIVE',
        'Suspended well': 'TA',
        'Unknown': 'UNKNOWN',
        'Water supply well': 'ACTIVE',
        'Administratively abandoned': 'ACTIVE',
        'Commingled well (triple), oil': 'ACTIVE',
        'Oil well, single completion': 'ACTIVE',
        'Water injection, dual completion': 'ACTIVE',
        'Gas well, dual completion': 'ACTIVE',
        'Gas injection, single completion': 'ACTIVE',
        'Commingled well (dual), oil': 'ACTIVE',
        'Water injection, single pool, two tbg strings': 'ACTIVE',
        'Disposal injection well, Class 2': 'ACTIVE',
        'Plugged & Abandoned': 'PA',
        'Surface Plug': 'TA',
        'Observation well': 'ACTIVE',
        'Permit cancelled': 'CANCELLED',
        'Gas well (dual) & Storage well': 'ACTIVE',
        'Sqzd orig hole w/mult laterals': 'ACTIVE',
        'Geothermal': 'ACTIVE',
        'Gas well, single completion': 'ACTIVE',
        'Gas well & Storage well': 'ACTIVE',
    },
    'category_map': {
        'Development': 'CONVENTIONAL',
        'Exploratory': 'TEST',
        'Service': 'SERVICE',
        'Stratigraphic Test': 'TEST',
    }
}