layout = {
    'date_field': ['SPUD DATE', 'FIRST COMPLETION DATE', 'FIRST PRODUCTION DATE'],
    'api_field': 'API NUMBER',
    'type_field': 'STANDARD WELL TYPE DESCRIPTION',
    'status_field': 'STANDARD WELL STATUS DESCRIPTION',
    'category_field': 'STATE WELL TYPE',
    'lat_field': 'WELLHEAD LATITUDE, DECIMAL DEGREES',
    'lon_field': 'WELLHEAD LONGITUDE, DECIMAL DEGREES',
    'description_layout': '\n'.join(['WELL NAME: %s',
                             'WELL NUMBER: %s',
                             'OPERATOR: %s',
                             'COUNTY: %s',
                             'FIELD NAME: %s'
                            ]),
    'description_fields': ['WELL NAME', 'WELL NUMBER', 'OPERATOR', 'COUNTY', 'FIELD NAME'],
    'type_map': {
        'Underground Injection Control:Class 2 Disposal': 'DISPOSAL',
        'Unassigned': 'UNKNOWN',
        'Permit': 'UNKNOWN',
        'Coal Bed Methane': 'GAS',
        'Underground Injection Control:Class 2 Enhanced Recovery': 'SERVICE',
        'Water Supply': 'WATER',
        'Unknown': 'UNKNOWN',
        'Gas': 'GAS',
        'Gas Storage': 'STORAGE',
        'Other': 'OTHER',
        'Oil': 'OIL',
        'Brine Supply': 'WATER',
    },
    'status_map': {
        'Active:Producing': 'ACTIVE',
        'Abandoned': 'A',
        'Permit:Active': 'ACTIVE',
        'Abandoned:Plugged': 'PA',
        'Permit:Cancelled Expired': 'CANCELLED',
        'Inactive:Temporarily Abandoned': 'TA',
        'Inactive:Shut In': 'SI',
        'Unknown': 'UNKNOWN',
        'Unassigned': 'UNKNOWN',
        'Active': 'ACTIVE',
        'Active:Completed': 'ACTIVE',
    },
    'category_map': {
        'Need Code': 'UNKNOWN',
        'Oil - Production': 'CONVENTIONAL',
        'Seismic-exploratory Well': 'TEST',
        'Salt Water Injection': 'SERVICE',
        'Natural Gas - Dry': 'CONVENTIONAL',
        'Brine Injection Well': 'SERVICE',
        'Brine Supply Well': 'SERVICE',
        'Coal Bed Methane': 'CBM',
        'Salt Water Disposal': 'SERVICE',
        'Coal Bed Methane Service Well': 'SERVICE',
        'Enhanced Oil Recovery': 'FRAC',
        'Water Supply': 'SERVICE',
        'Unknown': 'UNKNOWN',
        'Expired Permit': 'UNKNOWN',
        'Gas Injector': 'SERVICE',
        'Gas Storage': 'STORAGE',
        'Waste Disposal Well': 'SERVICE',
        'Service Well': 'SERVICE',
    }
}