source_url = 'https://igs.indiana.edu/pdms/map/'
description = """
Oil and gas records retrieved from the Indiana Geological Survey. Well location data is
retrieved from the Petroleum Database Managment System at <a href="https://igs.indiana.edu/pdms/map/"
target="_blank">https://igs.indiana.edu/pdms/map/</a>. Well status information is retrieved
by querying the PDMS well record tables at: https://igs.indiana.edu/PDMS/WellSearch.cfm
All locations are assumed to be surface locations.
Indiana does not identify its wells using API numbers. For the purposes of our database,
we have used the two digit state prefix plus the IGS_ID to identify Indiana wells.
"""
# IN Well Symbols and Statuses: https://igs.indiana.edu/pdms/Help/index.htm#t=Petroleum_Well_Symbols.htm
layout = {
    'date_field': 'SpudDate',
    'api_field': 'IGS_ID',
    'type_field': 'SYMBOL',
    'status_field': 'Status',
    'lat_field': 'y',
    'lon_field': 'x',
    'description_layout': '\n'.join(['County: %s',
                             'Field Name: %s',
                             'IGS ID: %s',
                             'IGS Reported Status: %s',
                             'Link: <a href="https://igs.indiana.edu/pdms/wellEvents.cfm?igsID=%s">IGS link</a>'
                            ]),
    'description_fields': ['COUNTY', 'FIELD_NAME', 'IGS_ID', 'Status', 'IGS_ID'],
    'type_map': {
        'OAG': 'OILANDGAS',
        'AGAS-C': 'GAS',
        'AOIL': 'OIL',
        'AWIO': 'INJECTION',
        'GSG': 'STORAGE',
        'ASWDO': 'DISPOSAL',
        'AGAS-L': 'GAS',
        'AWIG': 'INJECTION',
        'AOAG-LC': 'OILANDGAS',
        'GSO': 'STORAGE',
        'AOIL-C': 'OIL',
        'NPWSO': 'WATER',
        'TAOIL': 'OIL',
        'GAS': 'GAS',
        'AOIL-L': 'OIL',
        'AGAS': 'GAS',
        'AOAG-L': 'OILANDGAS',
        'AOAG-C': 'OILANDGAS',
        'AOIL-LC': 'OIL',
        'WIOG': 'INJECTION',
        'OBG': 'OBSERVATION',
        'ASWDG': 'DISPOSAL',
        'AGSO': 'STORAGE',
        'AGAS-LC': 'GAS',
        'AGSG': 'STORAGE',
        'WIG': 'INJECTION',
        'SWDO': 'DISPOSAL',
        'OIL': 'OIL',
        'TAGAS': 'GAS',
        'WIO': 'INJECTION',
        'SWDG': 'DISPOSAL',
        'TAOG': 'OILANDGAS',
        'AOAG': 'OILANDGAS',
        'AWIOG': 'INJECTION',
    },
    'status_map': {
        '': 'UNKNOWN',
        'junked': 'A',
        'dry hole': 'DRY',
        'potable water supply': 'UNKNOWN',
        'pilot hole': 'DRY',
        'replacement for revoked permit': 'UNKNOWN',
        'revoked permit': 'CANCELLED',
        'gas': 'ACTIVE',
        'cancelled permit': 'CANCELLED',
        'permit for abandonment': 'A',
        'gas injection': 'ACTIVE',
        'sump hole': 'ACTIVE',
        'stratigraphic/structure test': 'DRY',
        'permit not used': 'PERMITTED',
        'location': 'UNKNOWN',
        'oil and gas': 'ACTIVE',
        'repermitted to drill deeper': 'ACTIVE',
        'workover': 'UNKNOWN',
        'revised permit': 'UNKNOWN',
        'expired permit': 'CANCELLED',
        'change of operator': 'UNKNOWN',
        'non-potable water supply': 'ACTIVE',
        'plugged': 'PA',
        'oil': 'ACTIVE',
        'permit number assigned to old well': 'UNKNOWN',
        'location changed': 'UNKNOWN',
        'waste disposal': 'ACTIVE',
        'salt water disposal': 'ACTIVE',
        'non-commercial gas': 'ACTIVE',
        'temporarily abandoned': 'TA',
        'new lease name or well number': 'PERMITTED',
        'Active': 'ACTIVE',
        'water injection (flood)': 'ACTIVE',
        'abandoned location': 'A',
        'gas storage': 'ACTIVE',
        'unknown': 'UNKNOWN',
        'observation': 'ACTIVE',
    },

}