layout = {
    'api_field': 'API_NUMBER',
    'date_field': ['SPUD_DATE', 'COMPLETION_DATE','PLUG_DATE'],
    'lat_field': 'NAD83_LATITUDE',
    'lon_field': 'NAD83_LONGITUDE',
    'status_field': 'STATUS_TXT',
    'status_map': {
        'Other, Plugged': 'PA',
        'Intent': 'UNKNOWN',
        'Oil': 'ACTIVE',
        'Other': 'UNKNOWN',
        'Coal Bed Methane, Plugged': 'PA',
        'Salt Water Disposal, Plugged': 'PA',
        'Coal Bed Methane': 'ACTIVE',
        'Enhanced Oil Recovery': 'ACTIVE',
        'Gas': 'ACTIVE',
        'Location': 'UNKNOWN',
        'Oil and Gas, Plugged': 'PA',
        'Injection, Plugged': 'PA',
        'Injection': 'ACTIVE',
        'Oil, Plugged': 'PA',
        'Gas, Plugged': 'PA',
        'Salt Water Disposal': 'ACTIVE',
        'Dry and Abandoned': 'DRY',
        'Enhanced Oil Recovery, Plugged': 'PA',
        'Oil and Gas': 'ACTIVE',
    },
    'type_field': 'STATUS_TXT',
    'type_map': {
        'Other, Plugged': 'OTHER',
        'Intent': 'UNKNOWN',
        'Oil': 'OIL',
        'Other': 'OTHER',
        'Coal Bed Methane, Plugged': 'GAS',
        'Salt Water Disposal, Plugged': 'DISPOSAL',
        'Coal Bed Methane': 'GAS',
        'Enhanced Oil Recovery': 'OIL',
        'Gas': 'GAS',
        'Location': 'UNKNOWN',
        'Oil and Gas, Plugged': 'OILANDGAS',
        'Injection, Plugged': 'INJECTION',
        'Injection': 'INJECTION',
        'Oil, Plugged': 'OIL',
        'Gas, Plugged': 'GAS',
        'Salt Water Disposal': 'DISPOSAL',
        'Dry and Abandoned': 'DRY HOLE',
        'Enhanced Oil Recovery, Plugged': 'OIL',
        'Oil and Gas': 'OILANDGAS',
    },    
}

"""
'type_field': 'WELL_TYPE',
    'type_map': {
        '': 'OTHER',
        'J&A': 'UNKNOWN',
        'NHDW': 'UNKNOWN',
        'WATER': 'WATER',
        'CBM': 'GAS',
        'OIL&SWD': 'OIL',
        '2 OIL': 'OIL',
        'SHUT-IN': 'UNKNOWN',
        'D&A': 'UNKNOWN',
        'INJ OR ': 'INJECTION',
        'GAS': 'GAS',
        'OIL&W-INJ': 'OIL',
        'OBSERVATION': 'OBSERVATION',
        'LOC': 'TEST',
        'EOR': 'UNKNOWN',
        'GAS-INJ': 'INJECTION',
        'OTHER': 'OTHER',
        'OIL/GAS': 'OILANGAS',
        'OIL-SWD': 'OIL',
        'OBS': 'OBSERVATION',
        'GAS INJ': 'INJECTION',
        'P&A': 'UNKNOWN',
        'COREHOLE': 'TEST',
        'NULL': 'UNKNOWN',
        'OIL': 'OIL',
        'MONITOR': 'OBSERVATION',
        '2OIL': 'OIL',
        'OIL&GAS-INJ': 'INJECTION',
        'INJ or EOR': 'INJECTION',
        'EXPIRED': 'UNKNOWN',
        'GAS-STG': 'STORAGE',
        'SWD': 'DISPOSAL',
        'W-INJ': 'INJECTION',
        'INJ OR EOR': 'INJECTION',
        'HELIUM': 'OTHER',
        'CLASS1': 'UNKNOWN',
        'CLASS ONE (OLD)': 'UNKNOWN',
        'GSW': 'STORAGE',
        'INJ': 'INJECTION',
        '1O&1G': 'OILANDGAS',
        'OIL,SWD': 'OIL',
        'ABD LOC': 'UNKNOWN',
        'LH': 'UNKNOWN',
        'TEMP ABD': 'UNKNOWN',
        'TA': 'UNKNOWN',
        'CATH': 'UNKNOWN',
        'GAS&SWD': 'GAS',
        'ABND': 'UNKNOWN',
        'O&G': 'OILANDGAS',
        'STRAT': 'TEST',
        '1O&1SWD': 'OIL',
    },
    'category_field': 'WELL_CLASS',
    'category_map': None
"""