layout = {
    'api_field': 'API_NUMBER',
    'date_field': ['COMP_DATE', 'PERMIT_DATE'],
    'lat_field': 'LATITUDE',
    'lon_field': 'LONGITUDE',
    'status_field': 'STATUSLONG',
    'status_map': {
        '': 'UNKNOWN',
        'Temporarily Abandoned, Plugged': 'TA',
        'Water Injection Well': 'ACTIVE',
        'Junked and Abandoned': 'A',
        'Detergent Injection Well': 'ACTIVE',
        'Temporarily Abandoned, Oil and Gas Shows': 'TA',
        'Oil Producer, Plugged': 'PA',
        'Confidential Hole': 'UNKNOWN',
        'Combination Oil and Gas Producer': 'ACTIVE',
        'Corrosion Protection Plugged': 'PA',
        'Coal Slurry Injection Well': 'ACTIVE',
        'Observation Well, Oil & Gas Shows': 'ACTIVE',
        'Dry and Abandoned, Gas Shows, Plugged': 'PA',
        'Junked and Abandoned, Oil Shows': 'A',
        'Observation Well': 'ACTIVE',
        'Waste Disposal Well': 'ACTIVE',
        'Gas Injection Well': 'ACTIVE',
        'Corrosion Protection': 'UNKNOWN',
        'Undesignated Injection Well': 'ACTIVE',
        'Temporarily Abandoned, Oil Shows': 'TA',
        'Observation Well, Oil Shows, Plugged': 'PA',
        'Chemical Injection Well, Plugged': 'PA',
        'Temporarily Abandoned, Oil Shows, Plugged': 'PA',
        'Water Injection Well, Oil and Gas Shows': 'ACTIVE',
        'Dry and Abandoned, No Shows, Plugged': 'PA',
        'Methane Vent': 'ACTIVE',
        'Dry and Abandoned, Administratively Plugged': 'PA',
        'Stratigraphic Test': 'A',
        'Structure Test, Plugged': 'PA',
        'Structure Test': 'A',
        'Coal Mine Methane, Plugged': 'PA',
        'Gas Injection Well, Plugged': 'PA',
        'Air Injection Well': 'ACTIVE',
        'Water Supply Well': 'ACTIVE',
        'Dry and Abandoned, Oil Shows': 'A',
        'Water Injection and Water Supply': 'ACTIVE',
        'Salt Water Disposal, Service Well': 'ACTIVE',
        'Steam Injection Well, Plugged': 'PA',
        'Combination Oil Producer and Water Injection': 'ACTIVE',
        'Air Injection Well, Plugged': 'PA',
        'Salt Water Disposal and Water Injection': 'ACTIVE',
        'Oil Well and Salt Water Disposal, Plugged': 'PA',
        'Coal Bed Methane': 'PA',
        'Unknown': 'UNKNOWN',
        'Observation Well, Plugged': 'PA',
        'Salt Producer, Oil Shows': 'ACTIVE',
        'Observation Well, Gas Shows': 'ACTIVE',
        'Coal Mine Methane': 'ACTIVE',
        'Oil Producer': 'ACTIVE',
        'Dry and Abandoned, Oil and Gas Shows, Plugged': 'PA',
        'Combination Oil and Gas Producer, Plugged': 'PA',
        'Salt Water Disposal and Water Injection, Plugged': 'PA',
        'Water Injection Well, Oil Shows': 'ACTIVE',
        'Dry & Abandoned, left open for a water well': 'UNKNOWN',
        'Chemical Injection Well': 'ACTIVE',
        'Temporarily Abandoned': 'TA',
        'Comb. Oil Producer and Water Injection, Plugged': 'PA',
        'Gas Well, Administratiely Plugged': 'PA',
        'Methane Vent, Plugged': 'PA',
        'Gas Producer, Plugged': 'PA',
        'Coal Slurry Injection Well, Plugged': 'PA',
        'Dry Hole (water well)': 'DRY',
        'Unknown, Plugged': 'PA',
        'Salt Water Disposal, Service Well, Plugged': 'PA',
        'Abandoned Location': 'A',
        'Temporarily Abandoned, Oil and Gas Shows, Plugged': 'PA',
        'Plugged Hole': 'PA',
        'Dry and Abandoned, Oil Shows, Plugged': 'PA',
        'Gas Storage Well': 'ACTIVE',
        'Undesignated Injection Well, Plugged': 'PA',
        'Dry and Abandoned, No Shows': 'A',
        'Coal Bed Methane, Plugged': 'PA',
        'Water Injection Well, Plugged': 'PA',
        'Temporarily Abandoned, Gas Shows, Plugged': 'PA',
        'Oil Well and Salt Water Disposal': 'ACTIVE',
        'Junked and Abandoned, Oil and Gas Shows, Plugged': 'PA',
        'Junked and Abandoned, Oil Shows, Plugged': 'PA',
        'Observation Well, Oil Shows': 'ACTIVE',
        'Dry and Abandoned, Gas Shows': 'A',
        'Thermal Injection Well': 'ACTIVE',
        'Stratigraphic Test, Plugged': 'PA',
        'Water Supply Well, Plugged': 'PA',
        'Dry & Aband, left open for a water well, plugged': 'PA',
        'Dry and Abandoned, Oil and Gas Shows': 'A',
        'Temporarily Abandoned, Administratively Plugged': 'PA',
        'Oil Well, Administratively Plugged': 'PA',
        'Junked and Abandoned, Gas Shows': 'A',
        'Permit to Drill Issued': 'PERMITTED',
        'Water Injection and Water Supply, Plugged': 'PA',
        'Waste Disposal Well, Plugged': 'PA',
        'Gas Producer': 'ACTIVE',
        'Water Injection Well, Oil Shows, Plugged': 'PA',
        'Temporarily Abandoned, Gas Shows': 'TA',
        'Gas Storage Well, Plugged': 'PA',
        'Undesignated Injection Well, Admin. Plugged': 'PA',
        'Junked and Abandoned, Plugged': 'PA',
    },
    'type_field': 'STATUSLONG',
    'type_map': {
        '': 'UNKNOWN',
        'Temporarily Abandoned, Plugged': 'UNKNOWN',
        'Water Injection Well': 'WATER',
        'Junked and Abandoned': 'UNKNOWN',
        'Detergent Injection Well': 'INJECTION',
        'Temporarily Abandoned, Oil and Gas Shows': 'OILANDGAS',
        'Oil Producer, Plugged': 'OIL',
        'Confidential Hole': 'UNKNOWN',
        'Combination Oil and Gas Producer': 'OILANDGAS',
        'Corrosion Protection Plugged': 'UNKNOWN',
        'Coal Slurry Injection Well': 'OTHER',
        'Observation Well, Oil & Gas Shows': 'OBSERVATION',
        'Dry and Abandoned, Gas Shows, Plugged': 'GAS',
        'Junked and Abandoned, Oil Shows': 'OIL',
        'Observation Well': 'OBSERVATION',
        'Waste Disposal Well': 'DISPOSAL',
        'Gas Injection Well': 'INJECTION',
        'Corrosion Protection': 'UNKNOWN',
        'Undesignated Injection Well': 'INJECTION',
        'Temporarily Abandoned, Oil Shows': 'OIL',
        'Observation Well, Oil Shows, Plugged': 'OIL',
        'Chemical Injection Well, Plugged': 'INJECTION',
        'Temporarily Abandoned, Oil Shows, Plugged': 'OIL',
        'Water Injection Well, Oil and Gas Shows': 'OILANDGAS',
        'Dry and Abandoned, No Shows, Plugged': 'DRY HOLE',
        'Methane Vent': 'OTHER',
        'Dry and Abandoned, Administratively Plugged': 'DRY HOLE',
        'Stratigraphic Test': 'TEST',
        'Structure Test, Plugged': 'TEST',
        'Structure Test': 'TEST',
        'Coal Mine Methane, Plugged': 'GAS',
        'Gas Injection Well, Plugged': 'INJECTION',
        'Air Injection Well': 'INJECTION',
        'Water Supply Well': 'WATER',
        'Dry and Abandoned, Oil Shows': 'OIL',
        'Water Injection and Water Supply': 'WATER',
        'Salt Water Disposal, Service Well': 'DISPOSAL',
        'Steam Injection Well, Plugged': 'INJECTION',
        'Combination Oil Producer and Water Injection': 'OIL',
        'Air Injection Well, Plugged': 'INJECTION',
        'Salt Water Disposal and Water Injection': 'DISPOSAL',
        'Oil Well and Salt Water Disposal, Plugged': 'DISPOSAL',
        'Coal Bed Methane': 'GAS',
        'Unknown': 'UNKNOWN',
        'Observation Well, Plugged': 'OBSERVATION',
        'Salt Producer, Oil Shows': 'OTHER',
        'Observation Well, Gas Shows': 'OBSERVATION',
        'Coal Mine Methane': 'GAS',
        'Oil Producer': 'OIL',
        'Dry and Abandoned, Oil and Gas Shows, Plugged': 'OILANDGAS',
        'Combination Oil and Gas Producer, Plugged': 'OILANDGAS',
        'Salt Water Disposal and Water Injection, Plugged': 'INJECTION',
        'Water Injection Well, Oil Shows': 'INJECTION',
        'Dry & Abandoned, left open for a water well': 'DRY HOLE',
        'Chemical Injection Well': 'INJECTION',
        'Temporarily Abandoned': 'UNKNOWN',
        'Comb. Oil Producer and Water Injection, Plugged': 'OIL',
        'Gas Well, Administratiely Plugged': 'GAS',
        'Methane Vent, Plugged': 'OTHER',
        'Gas Producer, Plugged': 'GAS',
        'Coal Slurry Injection Well, Plugged': 'INJECTION',
        'Dry Hole (water well)': 'DRY HOLE',
        'Unknown, Plugged': 'UNKNOWN',
        'Salt Water Disposal, Service Well, Plugged': 'DISPOSAL',
        'Abandoned Location': 'UNKNOWN',
        'Temporarily Abandoned, Oil and Gas Shows, Plugged': 'OILANDGAS',
        'Plugged Hole': 'UNKNOWN',
        'Dry and Abandoned, Oil Shows, Plugged': 'OIL',
        'Gas Storage Well': 'STORAGE',
        'Undesignated Injection Well, Plugged': 'INJECTION',
        'Dry and Abandoned, No Shows': 'DRY HOLE',
        'Coal Bed Methane, Plugged': 'GAS',
        'Water Injection Well, Plugged': 'INJECTION',
        'Temporarily Abandoned, Gas Shows, Plugged': 'GAS',
        'Oil Well and Salt Water Disposal': 'OIL',
        'Junked and Abandoned, Oil and Gas Shows, Plugged': 'OILANDGAS',
        'Junked and Abandoned, Oil Shows, Plugged': 'OIL',
        'Observation Well, Oil Shows': 'OBSERVATION',
        'Dry and Abandoned, Gas Shows': 'GAS',
        'Thermal Injection Well': 'INJECTION',
        'Stratigraphic Test, Plugged': 'TEST',
        'Water Supply Well, Plugged': 'WATER',
        'Dry & Aband, left open for a water well, plugged': 'WATER',
        'Dry and Abandoned, Oil and Gas Shows': 'OILANDGAS',
        'Temporarily Abandoned, Administratively Plugged': 'UNKNOWN',
        'Oil Well, Administratively Plugged': 'OIL',
        'Junked and Abandoned, Gas Shows': 'GAS',
        'Permit to Drill Issued': 'UNKNOWN',
        'Water Injection and Water Supply, Plugged': 'WATER',
        'Waste Disposal Well, Plugged': 'DISPOSAL',
        'Gas Producer': 'GAS',
        'Water Injection Well, Oil Shows, Plugged': 'INJECTION',
        'Temporarily Abandoned, Gas Shows': 'GAS',
        'Gas Storage Well, Plugged': 'STORAGE',
        'Undesignated Injection Well, Admin. Plugged': 'INJECTION',
        'Junked and Abandoned, Plugged': 'UNKNOWN',
    },
}