# STATUS CODES: http://sonlite.dnr.state.la.us/sundown/cart_prod/cart_con_wellstcode
# TYPE COES: http://sonlite.dnr.state.la.us/sundown/cart_prod/CART_CON_prodtyplst
layout = {
    'api_field': 'API_NUM',
    'date_field': ['SPUD_DATE', 'PERMIT_DATE', 'ORIGINAL_COMPLETION_DATE', 'WELL_STATUS_DATE'],
    'lat_field': 'SURFACE_LAT_DEC_DEG',
    'lon_field': 'SURFACE_LONG_DEC_DEG',
    'status_field': 'WELL_STATUS_CODE',
    'status_map': {
        '01': 'PERMITTED',
        '02': 'PERMITTED',
        '03': 'CANCELLED',
        '08': 'TA',
        '09': 'ACTIVE',
        '10': 'ACTIVE',
        '11': 'ACTIVE',
        '16': 'ACTIVE',
        '17': 'ACTIVE',
        '18': 'TA',
        '19': 'A',
        '20': 'TA',
        '21': 'A',
        '22': 'ACTIVE',
        '23': 'ORPHAN',
        '24': 'UNKNOWN',
        '25': 'UNKNOWN',
        '26': 'ORPHAN',
        '28': 'ORPHAN',
        '29': 'PA',
        '30': 'PA',
        '31': 'SI',
        '32': 'SI',
        '33': 'SI',
        '34': 'SI',
        '35': 'PA',
        '36': 'SI',
        '37': 'SI',
        '46': 'ACTIVE',
        '49': 'ACTIVE',
        '73': 'ACTIVE',
        '80': 'UNKNOWN',
        '82': 'ACTIVE',
        '90': 'PA',
        'ZZZZZ': 'UNKNOWN',
    },
    'type_field': 'PRODUCT_TYPE_CODE',
    'type_map': {
        '00': 'UNKNOWN',
        '10': 'OIL',
        '20': 'GAS',
        '25': 'GAS',
        'ZZZZZ': 'UNKNOWN',
    },
}