# Well Type and Status http://www.michigan.gov/deq/0,4561,7-135-3306_6828-9311--,00.html
# the date fields appear to be all empty. may require some supplemental scraping
layout = {
    'api_field': 'api_wellno',
    'date_field': ['PermDate','PlugDate'],
    'lat_field': 'bh_lat',
    'lon_field': 'bh_long',
    'status_field': 'well_stat',
    'status_map': {
        'Active': 'ACTIVE',
        'Domestic Well': 'ACTIVE',
        'Drilling Completed': 'ACTIVE',
        'Orphan': 'ORPHAN',
        'Permitted Well': 'PERMITTED',
        'Pilot': 'ACTIVE',
        'Plugged Back': 'PA',
        'Plugging Approved': 'PA',
        'Plugging Completed': 'PA',
        'Producing': 'ACTIVE',
        'Shut_In': 'SI',
        'Suspended Operations': 'TA',
        'Temporarily Abandoned': 'TA',
        'Terminated Permit': 'CANCELLED',
        'Unknown': 'UNKNOWN',
        'Water Supply': 'ACTIVE',
        'Well Completed': 'ACTIVE',
    },
    'type_field': 'well_type',
    'type_map': {
        'BDW': 'DISPOSAL',
        'BR': 'UNKNOWN',
        'DH': 'DRY HOLE',
        'GAS': 'GAS',
        'GBD': 'GAS',
        'GC': 'GAS',
        'GIW': 'INJECTION',
        'GS': 'STORAGE',
        'GSO': 'OBSERVATION',
        'LHL': 'UNKNOWN',
        'LOC': 'UNKNOWN',
        'LPG': 'STORAGE',
        'MDW': 'DISPOSAL',
        'MNB': 'WATER',
        'MSM': 'WATER',
        'MSW': 'STORAGE',
        'MTW': 'TEST',
        'OBS': 'OBSERVATION',
        'OIL': 'OIL',
        'OTH': 'OTHER',
        'OTI': 'INJECTION',
        'SO': 'OTHER',
        'TH': 'OTHER',
        'UN': 'OTHER',
        'WIW': 'INJECTION',
    },
}